---
# Credentials for CVP and EOS Switches
ansible_user: cvpadmin
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"

ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
ansible_diff_mode: network

# Local Users
aaa_settings:
  local_users:
    - name: "{{ ansible_user }}"
      privilege: 15
      role: network-admin
      sha512_password: "{{ ansible_password | password_hash('sha512', salt=lookup('env', 'AVD_PASSWORD_SALT') | default('arista', true), rounds=100000) }}"
      ssh_key: "{{ ' '.join(lookup('ansible.builtin.file', lookup('ansible.builtin.first_found', dict(files=['id_ed25519.pub', 'id_ecdsa.pub', 'id_rsa.pub'], paths=[lookup('env', 'HOME') + '/.ssh/']))).split()[:2]) }}"
    - name: "admin"
      privilege: 15
      role: network-admin
      sha512_password: "{{ ansible_password | password_hash('sha512', salt=lookup('env', 'AVD_PASSWORD_SALT') | default('arista', true), rounds=100000) }}"
      ssh_key: "{{ ' '.join(lookup('ansible.builtin.file', lookup('ansible.builtin.first_found', dict(files=['id_ed25519.pub', 'id_ecdsa.pub', 'id_rsa.pub'], paths=[lookup('env', 'HOME') + '/.ssh/']))).split()[:2]) }}"
    - name: service
      sha512_password: "{{ ansible_password | password_hash('sha512', salt=lookup('env', 'AVD_PASSWORD_SALT') | default('arista', true), rounds=100000) }}"
      shell: /bin/bash
    - name: pcapper
      shell: /bin/bash
      sha512_password: "{{ ansible_password | password_hash('sha512', salt=lookup('env', 'AVD_PASSWORD_SALT') | default('arista', true), rounds=100000) }}"
      ssh_key: "{{ ' '.join(lookup('ansible.builtin.file', lookup('ansible.builtin.first_found', dict(files=['id_ed25519.pub', 'id_ecdsa.pub', 'id_rsa.pub'], paths=[lookup('env', 'HOME') + '/.ssh/']))).split()[:2]) }}"

# # OOB Management network default gateway.
# mgmt_gateway: 192.168.2.1
mgmt_interface_vrf: default

# Common settings
load_interval:
  default: 30

# AAA
custom_structured_configuration_aaa_authorization:
  exec:
    default: local

custom_structured_configuration_management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    - name: default

# DHCP
custom_structured_configuration_ip_dhcp_snooping:
  enabled: true
  information_option:
    enabled: false

# banners
custom_structured_configuration_banners:
  login: |
    ***********************************************
    Go away!
    EOF

#alias
custom_structured_configuration_aliases: |
  alias cc clear counters
  alias cp clear platform trident counters
  alias senz show interface counter error | nz
  alias shmc show int | awk '/^[A-Z]/ { intf = ck216 } /, address is/ { print intf, }'
  alias snz show interface counter | nz
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
  alias ps_show_bess bash ps -ef | grep -i Bess
  alias check_terminattr show agent TerminAttr log | tail

eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true
