---

evpn_l3_multicast: true
underlay_multicast_pim_sm: true
igmp_snooping_enabled : true
default_igmp_snooping_enabled: true

underlay_routing_protocol: isis
overlay_routing_protocol: ebgp

# ACT Settings
act_add_cvp: false
act_veos_internet_access: true

digital_twin:
  environment: act
  fabric:
    act_username: cvpadmin2
    act_password: blabla

custom_node_type_keys:

  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20
    cv_tags_topology_type: spine
    connected_endpoints: true
    vtep: true
    network_services:
        l1: true
        l2: true
        l3: true
    default_overlay_address_families:
      - evpn
    default_evpn_encapsulation: vxlan
    underlay_router: true

eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

shutdown_interfaces_towards_undeployed_peers: false

### Management console ###
custom_structured_configuration_management_console:
  idle_timeout: 300

custom_structured_configuration_management_ssh:
  idle_timeout: 60
  connection:
    limit: 5

### DNS Domain ###
custom_structured_configuration_dns_domain: lab.example.com

custom_structured_configuration_clock:
  timezone: Canada/Eastern

custom_structured_configuration_ipv6_unicast_routing: false

custom_structured_configuration_interface_defaults:
  ethernet:
    shutdown: true

custom_structured_configuration_errdisable:
  recovery:
    causes:
      - name: bpduguard
        interval: 30
      - name: link-flap
        interval: 30

custom_structured_configuration_radius_server:
  servers:
    - host: radsec.beta.agni.arista.io
      tls:
        enabled: true
        ssl_profile: agni-server

custom_structured_configuration_aaa_server_groups:
  - name: agni-server-group
    type: radius
    servers:
      - server: radsec.beta.agni.arista.io tls

custom_structured_configuration_aaa_accounting:
  dot1x:
    default:
      type: "start-stop"
      methods:
        - method: group
          group: agni-server-group

custom_structured_configuration_aaa_authentication:
  dot1x:
    default: group agni-server-group

custom_structured_configuration_dot1x:
  dynamic_authorization: true
  system_auth_control: true
  protocol_lldp_bypass: true

custom_structured_configuration_static_routes:
  - vrf: Production
    prefix: 0.0.0.0/0
    next_hop: 10.1.99.1
    name: "Default_prod_iTransit_MX"

custom_structured_configuration_ip_dhcp_snooping:
  enabled: true
  information_option:
    enabled: false

# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
p2p_uplinks_mtu: 1500

# MGMT Interface
mgmt_interface_vrf: MGMT
