
# Default enabling of flow-tracking(IPFIX) for various interface types across the fabric.
# Flow Tracking can also be enabled/disabled under each of the specific data models.
# For general flow-tracking settings see `flow_tracking_settings`.
fabric_flow_tracking:

  # Enable flow-tracking on all fabric uplinks.
  uplinks:
    enabled: true

    # Flow tracker name as defined in flow_tracking_settings.
    # name: <str; default="FLOW-TRACKER">

  # Enable flow-tracking on all fabric downlinks.
  downlinks:
    enabled: true

    # Flow tracker name as defined in flow_tracking_settings.
    # name: <str; default="FLOW-TRACKER">

  # Enable flow-tracking on all endpoints ports.
  endpoints:
    enabled: true

    # Flow tracker name as defined in flow_tracking_settings.
    # name: <str; default="FLOW-TRACKER">

  # Enable flow-tracking on all p2p_links defined under l3_edge.
  l3_edge:
    enabled: true

    # Flow tracker name as defined in flow_tracking_settings.
    # name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all p2p_links defined under core_interfaces.
  # core_interfaces:
  #   enabled: <bool; default=False>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all MLAG peer interfaces.
  # mlag_interfaces:
  #   enabled: <bool; default=False>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all node.l3_interfaces and network-services tenants.vrfs.l3_interfaces.
  # l3_interfaces:
  #   enabled: <bool; default=False>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all node.l3_port_channels.
  # l3_port_channels:
  #   enabled: <bool; default=False>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all dps_interfaces.
  # dps_interfaces:
  #   enabled: <bool; default=True>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

  # # Enable flow-tracking on all direct WAN HA links.
  # direct_wan_ha_links:
  #   enabled: <bool; default=False>

  #   # Flow tracker name as defined in flow_tracking_settings.
  #   name: <str; default="FLOW-TRACKER">

# Define the flow tracking parameters for this topology.
flow_tracking_settings:

  # The options relevant only for flow tracker type sampled.
  sampled:
    encapsulation:
      ipv4_ipv6: true
      mpls: true
    sample: 10000 # <int; 1-4294967295; default=10000>
    hardware_offload:

      # Configure hardware offload for IPv4 traffic.
      ipv4: true

      # Configure hardware offload for IPv6 traffic.
      # ipv6: false

      # Minimum number of samples.
      threshold_minimum: 300

  # The options relevant only for flow tracker type hardware.
  hardware:
    record:

      # Enable software export of IPFIX data records.
      format_ipfix_standard_timestamps_counters: true
  trackers: 

      # Tracker Name
    - name: IPFIX_CAMPUS

      # The options relevant only for flow tracker type sampled.
      sampled:

        # Maximum number of entries in flow table.
        table_size: 100
        record_export:

          # Export MPLS forwarding information.
          mpls: true
      record_export:

        # Flow record inactive export timeout in milliseconds
        on_inactive_timeout: 10000 # <int; 3000-900000>

        # Flow record export interval in milliseconds
        on_interval: 10000 # <int; 1000-36000000>
      exporters:

          # Exporter Name
        - name: IPFIX_MandE
          collector:

            # Collector IPv4 address or IPv6 address or fully qualified domain name
            host: 127.0.0.1

            # Collector Port Number
            # port: <int; 1-65535>
          # format:
          #   ipfix_version: <int>

          # Local Source Interface
          local_interface: Loopback0

          # Template interval in milliseconds
          template_interval: 100000 # <int; 5000-3600000>      