---

port_profiles:

# SITE1 MX
  - profile: SITE1_MX_TRUNK
    mode: trunk
    vlans: "110,150,155,160,165,171-183"
    native_vlan: 110

  - profile: SITE1_TRANSIT
    mode: trunk
    vlans: "99"

  - profile: SITE1_TRANSIT2
    mode: trunk
    vlans: "199"

# WAN
  - profile: WAN_SITE5_ISP2
    mode: access
    vlans: "5"
  - profile: WAN_SITE5_ISP1
    mode: access
    vlans: "6"

# Wifi
  - profile: Wifi
    mode: access
    vlans: "111"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge


# Network MGMT
  - profile: NetworkMgmt_site1
    mode: access
    vlans: "112"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: NetworkMgmt_site2
    mode: access
    vlans: "212"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: NetworkMgmt_site3
    mode: access
    vlans: "312"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: NetworkMgmt_site5
    mode: access
    vlans: "512"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge

  # JXSVideoTraffic Blue
  - profile: VideoTrafficBlue_site1
    mode: access
    vlans: "130"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: VideoTrafficBlue_site2
    mode: access
    vlans: "230"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge

  # JXSVideoTraffic Red
  - profile: VideoTrafficRed_site1
    mode: access
    vlans: "131"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: VideoTrafficRed_site2
    mode: access
    vlans: "231"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge

# SRTTrafficBlue
  - profile: SRTTrafficBlue_site1
    mode: access
    vlans: "135"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
  - profile: SRTTrafficBlue_site2
    mode: access
    vlans: "235"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge

# HaivisionSRTTraffic Red
  - profile: SRTTrafficRed_site1
    mode: access
    vlans: "136"
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
